### ISSUE TITLE
How to use in HA

### ISSUE THREAD

**Issue by rlust** [arnonym/ha-plugins#1]
I have the plugin installed and connect to a SIP extension. I Do not see any services exposed. How do I use it in HA?

**Comment by arnonym** [comment]
As written in the readme you must use the `hassio.addon_stdin` service to send commands to the add-on. This is done in the "Action" part of an automation. You have to use the `Edit in YAML` from the tripple dot menu to be able to specify the whole command. 

If you have an idea how to make that clearer in the readme, I would like to hear that.

**Comment by rlust** [comment]
Got it now Thanks!

**Comment by arnonym** [comment]
Glad you got that working. I added the more detailed explanation to the readme.

Out of curiosity: what's your use case?
