### ISSUE TITLE
Manual install docker environment

### ISSUE THREAD

**Issue by eporsche** [arnonym/ha-plugins#100]
From my understanding in manual home assistant docker environement this addon wont run.
Even if I setup a docker container next to home assistant - I have no way of calling the service, correct? at least I do not see the hassio.addon_stdin service in my installation-

Do you know of any custom component which has the same ability as your addon?

**Comment by eporsche** [comment]
Got it to run with local config and some changes to the run.sh script. 

However I know get this:

20:21:56.216            pjsua_acc.c  ...SIP registration failed, status=408 (Request Timeout)
20:21:56.216            pjsua_acc.c  ...Scheduling re-registration retry for acc 0 in 304 seconds..
| 20:21:56.217729 [1] OnRegState: 408 Request Timeout 

I am trying to connect to a fritz.box. Network of the container is set to host. Softphone within the fritz.box with the name homeassistant. Not sure what I am doing wrong here.

![image](https://github.com/arnonym/ha-plugins/assets/3265129/b255d785-960c-4dbd-9b3d-6bf8cbf4a837)

**Comment by arnonym** [comment]
You mixed up the SIP1_ID_URI and SIP1_REGISTRAR_URI:
```
SIP1_ENABLED = "True"
SIP1_ID_URI = "sip:homeassistant@fritz.box"
SIP1_REGISTRAR_URI = "sip:fritz.box"
SIP1_REALM = "fritz.box"
SIP1_USER_NAME = "homeassistant"
SIP1_ANSWER_MODE = "LISTEN"
SIP1_PASSWORD = "password"
SIP1_SETTLE_TIME = "1"
SIP1_INCOMING_CALL_FILE = ""
```

**Comment by eporsche** [comment]
🤦 - it works! 😅 Thx, for the heads up and sorry about bothering.... was able to make a call to my phone!
