### ISSUE TITLE
add-on hanging if dtmf input is entered before message has finished playing 

### ISSUE THREAD

**Issue by newpond** [arnonym/ha-plugins#108]
I am still having problems with the add-on hanging randomly when you press a key entry before the message has completed.
unfortunately the "running"  status does not change when this happens, however I have noticed that the cpu goes down to 0.3% when it hangs so I have automation to restart it through that. although sadly a restart doesn't  necessarily fix it as can hang again on the first call after.
changing from piper tts to a mp3 media file seams to make it a bit better but for some reason it still reprocesses the file before it plays it for some reason.
im guesing ti could be to do with this file conversion, but if I'm using a static mp3 (although not through choice, it just seem to improve it a bit), can this not just be stored as the converted version? (im guessing it  is via the cache) but im using this as an emergency alert system so it shouldn't go off very often by which time the cache will have expired.
is there a way to ignore any key presses until after the message has been read?
 
I was using Vonage and now using Linphone sip if that makes any difference
 any help appreciated

**Comment by arnonym** [comment]
I've added the possibility to cache the converted audio. Please see the docs for details. Please report back if that's working for you.

**Comment by newpond** [comment]
Wow that’s freaky I pressed the install button on the update one second before your email came in!!!

I trust you had a good holiday!

I have this in my configuration.yaml
tts:
  platform: wyoming
  cache: true
  cache_dir: /config/tts.piper
  time_memory: 3000
  service_name: tts.piper
  base_url: http://192.168.1.43:8123 <http://192.168.1.43:8123/>

Is that not doing the same thing?

Also how long do the files stay in your new cache and do mp3 files get converted into another format first?

cheers

**Comment by newpond** [comment]
Great thanks
Ill. give it a go!!

**Comment by newpond** [comment]
Sorry when you say this, " You also need to set cache_audio: true on every message or audio_file you want to cache.”
Do you mean in the automaton script etc?

**Comment by newpond** [comment]
So…
I notice you mention dynamic messages but couldn’t see anything in the  GitHub relating to . What are they exactly?

Also  with the settle_time: 1 , used to set time  to wait for playing the message/actions/etc. after call was established,
Could this be split into to 2 commands, 
1 to settle the line, 
2 waait for the message to play

As the s coudlbe a work around for the problem the s case is about. (By not letting people press a button before the message has finish)

Cheers

**Comment by arnonym** [comment]
Release: I'll do this in my free time, so the answer must be: when it's done. 

Re-encode: yes, it will.

**Comment by arnonym** [comment]
Release: released :-)

**Comment by newpond** [comment]
excellent...you found some free time!! :-)
Loading it now, will keep testing and see if the problem comes back.

cheers Arne

reds
Jon
