### ISSUE TITLE
Error after update to 2016.6

### ISSUE THREAD

**Issue by Extreme79** [arnonym/ha-plugins#110]
After the latest update I got this error.. But repository seems to be here, so how can I solve? 
![Screenshot_2024-06-08-10-00-22-82_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/arnonym/ha-plugins/assets/33934444/00d61038-561a-47df-b560-034ab9020f73)

Repository still in the home assistant registry, the component works perfectly.
I tried to re-add it, but I can't because it's already in the registry.
And I can't remove because it's in use.
So.. What to do.. Ignore it?

**Comment by arnonym** [comment]
I've just updated to 2024.6.1 and everything looks fine. Home Assistant 2016.6 looks also very old. Did you time travel by accident?

**Comment by Extreme79** [comment]
> I've just updated to 2024.6.1 and everything looks fine. Home Assistant 2016.6 looks also very old. Did you time travel by accident?

Sorry, a little timetravel mistake 🤣

**Comment by Extreme79** [comment]
Simple remove and reinstall solved the issue. Sorry.
