### ISSUE TITLE
Is It Possible to Use Microphone and Speaker for Real-Time Voice Calls via SIP?

### ISSUE THREAD

**Issue by RubiRubsn** [arnonym/ha-plugins#117]
Hi,

Thanks for this awesome project! I’m looking to set up a door intercom system using the SIP integration. Is it possible to configure the system to handle real-time voice communication via a microphone and speaker, allowing two-way communication (similar to a regular phone)? If so, how would this be implemented?

**Comment by arnonym** [comment]
Currently ha-sip is meant to be a headless system and this feature is available nor planned.
