### ISSUE TITLE
sip_2 not handled

### ISSUE THREAD

**Issue by drummer3333** [arnonym/ha-plugins#13]
The README describes that you can use sip_1 to register a 2nd SIP account. In my Local installation the 2nd account is not handled and as I see in the current man branch the sip_1 config is not used.

**Comment by drummer3333** [comment]
Off topic: Plugin is working with Asterisk / freePBX just fine

**Comment by arnonym** [comment]
Did you accidentally look at the readme on the beta repo at https://github.com/arnonym/ha-plugins-next?

The support for 2 SIP accounts is currently in beta in that repo. I hope to release that soonish, but if you also have the time to test that I would appreciate that. There were a lot of changes on that version. You need to add that as an additional repo to your home assistant installation.

If you use that version you need to change that magic string to call stdin actions to `8cd50eef_ha-sip-next`. This is NOT reflected in the readme of that branch!

**Comment by arnonym** [comment]
The version with 2 supported SIP accounts is released now!
