### ISSUE TITLE
user_name: consists only of numbers

### ISSUE THREAD

**Issue by qtronixx** [arnonym/ha-plugins#15]
Hello! If the user_name: consists only of numbers, then we get an error when trying to save the configuration.
`not a valid value. Got {'sip_global': {'port': 5060, 'log_level': 5}, 'sip': {'enabled': True, 'registrar_uri': 'sip:sip.provider.com', 'id_uri': 'sip:808748@sip.provider.com', 'realm': '*', 'user_name': 8208748, 'password': 'passwd', 'answer_mode': 'listen', 'settle_time': 1, 'incoming_call_file': ''}, 'sip_2': {'enabled': False, 'registrar_uri': 'sip:fritz.box', 'id_uri': 'sip:anotheruser@fritz.box', 'realm': '*', 'user_name': 'anotheruser', 'password': 'secret', 'answer_mode': 'listen', 'settle_time': 1, 'inco...`

**Comment by arnonym** [comment]
Try to put the user name in quotes like `"8208748"`. 

I hope this is not your real password, otherwise I would change that ASAP!
