### ISSUE TITLE
🎶 Howto play sound file on answering an incoming call ?

### ISSUE THREAD

**Issue by bubizar** [arnonym/ha-plugins#23]
First of all: great job !
Everything works like a charm. Big thank.

I'd like to play a music when answering an incoming call.

A word about that in doc would be perfect.

**Comment by arnonym** [comment]
Currently it's only possible to play TTS messages. Which format would the music in you would like to play?

**Comment by bubizar** [comment]
Thank you for your reply.

.wav would be great. .mp3 even greater.
Allowing music or prerecorded voice message can make auto-answer messages more friendly.

**Comment by arnonym** [comment]
I've added the option to play audio files instead of TTS messages. Search for `audio_file` in the docs to find the respective syntax. Also note the note after the yaml box.

Have fun with the new feature! I would appreciate feed-back if this is working as you would expect it.

**Comment by bubizar** [comment]
🎆 Marvellous! 🎆

It has immediately & perfectly worked.

It is a qualityquick work!
THANK YOU @arnonym!
