### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by billytkid** [arnonym/ha-plugins#27]
I'm trying to add this to HA OS, but I get the following error:

"
Failed to install add-on
Can't install agellhaus/amd64-ha-sip:2.3: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.3&fromImage=agellhaus%2Famd64-ha-sip&platform=linux%2Famd64: Not Found ("manifest for agellhaus/amd64-ha-sip:2.3 not found: manifest unknown: manifest unknown")
"

Any ideas?

**Comment by arnonym** [comment]
That was an error on my part. 2.3 is currently in beta, and I merged to `main` to early. I removed 2.3 from that branch again, you should now be able to install 2.2. Maybe you need to "check for updates".

**Comment by billytkid** [comment]
Wow, that's incredible speed at fixing, thank you :)
