### ISSUE TITLE
SIP username cant contain certain combinations

### ISSUE THREAD

**Issue by billytkid** [arnonym/ha-plugins#28]
Hi again,

My SIP username is a combination of numbers + letters, 
eg = 2142341e12

The config allows numbers + letters: 1234242wwer
But it does not allow numbers + letters + numbers = 4142341e12

Saving the config gives an error .Failed to save add-on configuration, not a valid value. .

**Comment by arnonym** [comment]
Please try to put the username in quotes like `"1234242wwer"`.

**Comment by billytkid** [comment]
Sorted, thank you!

**Comment by arnonym** [comment]
Nice, I'll add a note to the readme for that.
