### ISSUE TITLE
Installation of the add-on fails on devices with little memory

### ISSUE THREAD

**Issue by FloR012** [arnonym/ha-plugins#3]
Hello, 
I tried to install the add-on directly from the repository as described, but it always fail with this output on the logfile:

make  --no-print-directory -C python
swig -I../../../../pjlib/include -I../../../../pjlib-util/include -I../../../../pjmedia/include -I../../../../pjsip/include -I../../../../pjnath/include -c++  -w312  -python -o pjsua2_wrap.cpp ../pjsua2.i
python3 setup.py build 
running build
running build_py
creating build
creating build/lib.linux-aarch64-3.9
copying pjsua2.py -> build/lib.linux-aarch64-3.9
running build_ext
building '_pjsua2' extension
creating build/temp.linux-aarch64-3.9
aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-PN012d/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-PN012d/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c pjsua2_wrap.cpp -o build/temp.linux-aarch64-3.9/pjsua2_wrap.o -g -O2 -DPJ_AUTOCONF=1 -I/include -O2 -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1 -fPIC -DPJMEDIA_USE_OLD_FFMPEG=1 -DPJMEDIA_USE_OLD_FFMPEG=1 -I/pjproject/pjlib/include -I/pjproject/pjlib-util/include -I/pjproject/pjnath/include -I/pjproject/pjmedia/include -I/pjproject/pjsip/include
aarch64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
make[1]: *** [Makefile:37: _pjsua2.so] Error 1
make: *** [Makefile:29: python] Error 2

Removing intermediate container 7354840e65f3

Any ideas how to fix this?
I have a pretty new installation of Home Assistant OS x64 on a raspberry pi 3

**Comment by arnonym** [comment]
Could be an Out Of Memory kill. What amount of memory does your Raspi 3 have?

**Comment by FloR012** [comment]
Okay, I have an raspberry pi 3B, it should have 1GB RAM. Any ideas to get around this?

**Comment by arnonym** [comment]
There is a way to pre-build the docker images and put them on docker hub, but I actually like that the build is done transparently on the device itself. If you want to do that yourself I can only point you in this direction:
 https://developers.home-assistant.io/docs/add-ons/publishing/

**Comment by FloR012** [comment]
I read the link you provided but I am not sure if I can manage to do this on my own. I read that it is possible to reduce the memory consumption of make with providing the -j switch to reduce the number of parallel processes. Can this be a possible solution?

**Comment by arnonym** [comment]
I don't think that pjsip does any parallelization while compiling, so I don't think so.

**Comment by ldsmovil** [comment]
Imposible to install on home assistant OS 2021.11.5.

Even freezes the system and not accessible , I had to power restart

Intel nuc 4gb ram, its a pity I would like to try this

**Comment by FloR012** [comment]
I finally managed to install it as i moved from Pi3@1GB to Pi4@4GB

**Comment by arnonym** [comment]
There are now pre-compiled images available which also speeds up installation a lot.
