### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by smeagel73** [arnonym/ha-plugins#32]
Is it possible to run the addon in a seperate container without using supervisor?

**Comment by arnonym** [comment]
The communication between home-assistant and the docker container (ha-sip) is done with `hassio.addon_stdin`, which just posts a payload into `stdin` of the running add-on. This would not work without supervisor, and you would need to establish another form of communication.

On the other hand the config options are also transported with a supervisor mechanisms.

So the answer is: not easily.

**Comment by smeagel73** [comment]
thank you for this information
