### ISSUE TITLE
pre and post message for audio_file

### ISSUE THREAD

**Issue by Bram-diederik** [arnonym/ha-plugins#33]
Is it possible to make a pre and post message option that can work in combination with audio_file.

I'm "finished" with my over engineered voicemail system. (https://github.com/Bram-diederik/asterisk-homeassistant-tools) I would like the option that i leave a spoken message.
But that also requires the options of the menu to be spoken out. 

I could cat together some wav files. but this would be a nice addition to your lovely addon.

**Comment by arnonym** [comment]
Hi Bram,

I guess what you really want, is a list of "audio" outputs (tts or file) to play after each other. I don't see a need for that currently, but you're free to create a pull request.

**Comment by Bram-diederik** [comment]
Oh no I'm going to cat together wav files. I don't know how to develop on home assistant. python is not my best programing language.
