### ISSUE TITLE
Hang up other SIP session possible?

### ISSUE THREAD

**Issue by billytkid** [arnonym/ha-plugins#35]
Hi, this isnt a bug, but I'm not sure if it's meant to work or not.

I have a SIP phone at home, and my gate calls the SIP phone when someone presses the gate buzzer (this is  on Home Assistant).

When I want to let someone in I hit a button in HA and it opens the gate.

I'd like HA to be able to hang up the SIP session on the other device, is that possible? I've configured both HA-SIP and my SIP phone on the same account.

Thanks!

**Comment by arnonym** [comment]
Hi Billy,

ha-sip can only hangup calls that are accepted or executed by ha-sip itself. If the door station is calling the sip phone there is no way for ha-sip to cancel that. Not sure if you meant that, if not please clarify.

Regards,
Arne

**Comment by billytkid** [comment]
Hi Arne, 
Thanks for getting back to me.
Yep that's exactly the use case I was trying to achieve, I'll have to see if I can do it another way.

Thanks!

**Comment by arnonym** [comment]
Thinking about that a bit more: if the door-station is still ringing the phone *and* ha-sip, you could try to accept the call and hang-up right after.

**Comment by billytkid** [comment]
Thats a great idea, will give that a go! Thank you

**Comment by arnonym** [comment]
Please report if it worked. I'm curious.

**Comment by billytkid** [comment]
That works perfectly, amazing!

I can even use the TTS to say on the intercom 'please come in'

Superb! Thank you
