### ISSUE TITLE
Feature-Request: Listen for incoming calls

### ISSUE THREAD

**Issue by pascaltippelt** [arnonym/ha-plugins#4]
Hi!

As I can see from your examples and your profile you're from Germany as I am and use one of the famous AVM Fritz!Boxes. Your Plugin works great for "outgoing" calls, but it would be really nice if you could listen to incoming calls too.

I for example hava a doorbell calling all house-phones via voip/sip, using the Fritz!Box "Rundruf" (call everybody) functionality. Those calls are unluckily not registered in the call monitor, so I can not let HA know someone is at the door. 

But if you could make your addon listen to incoming calls, maybe even detecting the caller-id, this would massively improove my experience.

Best

Pascal

**Comment by arnonym** [comment]
Hi Pascal,

I discussed that use-case in the home-assistant community already and I think it's a great idea, but as I personally won't use that I won't implement that.

Non the less, I'm interested how the flow of the incoming call would be. I see 2 possibilities.

1. Have the incoming call as an event in home-assistant and react on that (e.g. use the existing functionality to call the house telephones)

2. React on the phone call in the add-on and dial a phone number and even connect the incoming call with the outgoing one to allow talking with the door station.

Option 1 would probably much easier to implement using the Webhook API end-point [0].

If you would like to implement anything like that yourself, I'm open to pull requests.

Regards,
Arne


[0] https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger

**Comment by pascaltippelt** [comment]
Hi Arne,

thank you. None of your use-cases are completely what I would expect. This is, because my doorbell can only ring a phone, but there is no audio-contact. But I can press a number (0 to 9), causing an action at the door (opeing the door...).

So my use-case would be:

1. Detect an incoming call
2. Sending an Notification to a receiver via notify, possebly then starting an action on HA

But everything except 1 would not be "your business". If a incoming call would raise an event would really be enougth, getting a caller id would be perfect.

Regards
Pascal

**Comment by arnonym** [comment]
ha-sip will now send an webhook event on incoming calls on the registered phone number. Please test if this is working for you.

**Comment by pascaltippelt** [comment]
I'm trying, but I alredy struggle to add your repository. I just get "Invalid Add-on repository!" when adding. Might be a problem on my side tho.

`Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 19:36:07 (1 occurrences)
Last logged: 19:36:07
Failed to to call /supervisor/options - Invalid Add-on repository!`

**Comment by arnonym** [comment]
I had a similar problem and it was fixed by restarting the supervisor.

**Comment by pascaltippelt** [comment]
Okay, repo is now ok, but the Addon does not show up.

**Comment by arnonym** [comment]
Did you click on the "Add-in Store" button in the right bottom corner?

**Comment by pascaltippelt** [comment]
It works very well.

Thank you for the lightning fast integration!

**Comment by arnonym** [comment]
Thanks for your feed-back! Happy to help.
