### ISSUE TITLE
Blind transfer a call?

### ISSUE THREAD

**Issue by pergolafabio** [arnonym/ha-plugins#50]
Hey, just found out this new addon, i saw it can register an account, with listen mode
My goal, i want to register an (trunk) on my door intercom, thats running a SIP server

On incoming call, i want to blind transfer it to another number like 1234@sip.linphone.org  

Is that possible?
Does your addon also support video ?

**Comment by arnonym** [comment]
Can you please describe which use-case you're solving with that?

**Comment by pergolafabio** [comment]
Well, my use case, I want to use this plugin to register on my doorbell (running an sip server) ... Then on incoming call, I want to transfer the call to a Linphone user or some other trunk in asterisk

**Comment by arnonym** [comment]
Why wouldn't you call the linphone user directly? Where is the additional value?

**Comment by pergolafabio** [comment]
Vecause, if i want to register directly with a linphone user (mobile/cellular, i need to open ports on firewall to my intercom)
This plugis local, if it receives the call, i can just forward it to sip.linphone.org
Or  i can forward the call to Asterisk and from there i can do group dialing or other stuff

**Comment by arnonym** [comment]
I've added a transfer call command in 2.9.

**Comment by pergolafabio** [comment]
Wow, great, will test it out soon!!

**Comment by pergolafabio** [comment]
Hi, i was testing this plugin out for first time, but am i correct the transfer only works in "accept" mode ?

If i try "listen " mode i receive a bad request.... is it possible to make also blind transfer possible? I dont want to answer call firsr, the caller should be still ringing 

Also, do you have plans to integrate video as well ?

09:24:19.733    evsub0x7f1d0dcb77c8  .....Subscription state changed ACTIVE --> TERMINATED
09:24:19.733           pjsua_call.c  .......Xfer client subscription terminated
| 09:24:19.733076 [1] onCallTransferStatus. Status code: 400 (Bad Request)

**Comment by marcolinux46** [comment]
Hi @pergolafabio,

did you test the transfer mode?
How does it work?
I mean, in the number field which is the data i have to insert? 
Can i transfer the call to an external number?

The same questions are for bridge mode

My use-case is: 
I call the ha-sip registered number from an external endpoint.
I trigger an automation through incoming-call webhook
I would like to transfer or bridge the call with my cell-phone number

Any ideas?

I created an automation that answer a call but i can't transfer it

Thanks for your support

**Comment by marcolinux46** [comment]
This is the message from log when starts the transfer:

Warning: call not in progress: sip:**622@192.xxx.xxx.xxx

**Comment by pergolafabio** [comment]
Yeah, I tested it succesfull, I had the same error message as you before, in the number field. , You need to enter the short number like "622" and not like sip:622@....

Also the call needs to be answered before you can transfer

**Comment by arnonym** [comment]
Hi @pergolafabio,
 
I've looked into blind transfer but I couldn't find anything regarding that in the pjsip library I'm using and all my tests failed. So if you have an idea how this could work with pjsip, keep it coming.

Arne

**Comment by pergolafabio** [comment]
Hey, no problem, I stopped using this addon, since it was giving issues with Linphone and no video..

The transfer worked , but only when call was accepted, thnx for investigation!

**Comment by arnonym** [comment]
Is this because there is no TLS support in ha-sip?

**Comment by pergolafabio** [comment]
Yeah, I think so

**Comment by marcolinux46** [comment]
> Yeah, I tested it succesfull, I had the same error message as you before, in the number field. , You need to enter the short number like "622" and not like sip:622@....
> 
> Also the call needs to be answered before you can transfer

Thanks @pergolafabio for your quick reply.

I try to input "**622" (i use a fritzbox as pbx server) in the number field for transfer but nothing happen.

I think that if i start the call from endpoint every mode doesn't work.
Instead of i start the call from the add-on every mode is working
