### ISSUE TITLE
Can't start the add-on

### ISSUE THREAD

**Issue by Marc1200** [arnonym/ha-plugins#54]
13:27:02.671           pjsua_core.c  .Error setting nameserver: Invalid DNS nameserver address (PJLIB_UTIL_EDNSINNSADDR) 

i get this error with the add-on, when i start it, after the error, it shuts down.
![image](https://github.com/arnonym/ha-plugins/assets/68737063/6486dc74-5242-44f0-8b68-07fdaca252ab)

**Comment by arnonym** [comment]
Please try using an IP address for the nameserver.

**Comment by arnonym** [comment]
Closed because of inactivity.

**Comment by Marc1200** [comment]
Sorry i forget to reply

It was indeed the wrong ip or dns, with the right dns it connects, but i got 403 forbidden error. our telephone provider does not allow to use SIP behind the modem, if the modem already used the SIP telephone

**Comment by orxaz** [comment]
Hi,

Same problem here...

Where do I have to configure nameserver? My operating system is correctly configured, resolving DNS queries flawlessly, but I don't know why de plugin always says me this:

```
11:17:05.760         sip_endpoint.c  .Module "mod-pjsua-log" registered
11:17:05.776           pjsua_core.c  .Error setting nameserver: Invalid DNS nameserver address (PJLIB_UTIL_EDNSINNSADDR) [status=320044]
11:17:05.776           endpoint.cpp  pjsua_init(&ua_cfg, &log_cfg, &med_cfg) error: Invalid DNS nameserver address (PJLIB_UTIL_EDNSINNSADDR) (status=320044) [../src/pjsua2/endpoint.cpp:1969]
Traceback (most recent call last):
```

**Comment by orxaz** [comment]
Found it, you can ignore this, sorry.
