### ISSUE TITLE
Can't start the addon

### ISSUE THREAD

**Issue by stefanoc78** [arnonym/ha-plugins#57]
Good evening,
big project...
unfortunately I can't start the addon, I've tried different configurations but always with the same negative result, I'm attaching the complete log below. Thanks in advance for any help you can give me. 
Stefano

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Python 3.10.11
| 21:44:13.706427 [ ] Setting name server: ['192.168.188.74']
| 21:44:13.706618 [1] No file name for incoming call config specified.
| 21:44:13.706761 [2] No file name for incoming call config specified.
| 21:44:13.706851 [3] No file name for incoming call config specified.
21:44:13.710         os_core_unix.c !pjlib 2.13 for POSIX initialized
21:44:13.712         sip_endpoint.c  .Creating endpoint instance...
21:44:13.713                  pjlib  .select() I/O Queue created (0x7f9731f150)
21:44:13.713         sip_endpoint.c  .Module "mod-msg-print" registered
21:44:13.713        sip_transport.c  .Transport manager created.
21:44:13.713           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
21:44:13.713         sip_endpoint.c  .Module "mod-pjsua-log" registered
21:44:13.714           pjsua_core.c  .Nameserver 192.168.188.74 added
21:44:13.714         sip_endpoint.c  .Module "mod-tsx-layer" registered
21:44:13.714         sip_endpoint.c  .Module "mod-stateful-util" registered
21:44:13.714         sip_endpoint.c  .Module "mod-ua" registered
21:44:13.714         sip_endpoint.c  .Module "mod-100rel" registered
21:44:13.714         sip_endpoint.c  .Module "mod-pjsua" registered
21:44:13.714         sip_endpoint.c  .Module "mod-invite" registered
21:44:13.732             alsa_dev.c  ..ALSA driver found 0 devices
21:44:13.732             alsa_dev.c  ..ALSA initialized
21:44:13.732                  pjlib  ..select() I/O Queue created (0x7f972f6058)
21:44:13.746         sip_endpoint.c  .Module "mod-evsub" registered
21:44:13.747         sip_endpoint.c  .Module "mod-presence" registered
21:44:13.747         sip_endpoint.c  .Module "mod-mwi" registered
21:44:13.747         sip_endpoint.c  .Module "mod-refer" registered
21:44:13.747         sip_endpoint.c  .Module "mod-pjsua-pres" registered
21:44:13.747         sip_endpoint.c  .Module "mod-pjsua-im" registered
21:44:13.747         sip_endpoint.c  .Module "mod-pjsua-options" registered
21:44:13.747           pjsua_core.c  .No SIP worker threads created
21:44:13.747           pjsua_core.c  .pjsua version 2.13 for Linux-6.1.21/aarch64 initialized
21:44:13.747           pjsua_core.c  .PJSUA state changed: CREATED --> INIT
| 21:44:13.747754 [ ] Supported audio codecs: speex/16000/1, speex/8000/1, speex/32000/1, iLBC/8000/1, GSM/8000/1, PCMU/8000/1, PCMA/8000/1, G722/16000/1, opus/48000/2, L16/44100/2, L16/44100/1
21:44:13.747            pjsua_aud.c  Setting null sound device..
21:44:13.747            pjsua_aud.c  .Opening null sound device..
21:44:13.748           pjsua_core.c  bind() error: Address in use [status=120098]
21:44:13.748           endpoint.cpp  pjsua_transport_create(type, &tcfg, &tid) error: Address in use (status=120098) [../src/pjsua2/endpoint.cpp:2243]
Traceback (most recent call last):
  File "/ha-sip/main.py", line 219, in <module>
    main()
  File "/ha-sip/main.py", line 202, in main
    end_point = sip.create_endpoint(endpoint_config)
  File "/ha-sip/sip.py", line 31, in create_endpoint
    end_point.transportCreate(pj.PJSIP_TRANSPORT_UDP, sip_tp_config)
  File "/root/.local/lib/python3.10/site-packages/pjsua2-2.13-py3.10-linux-aarch64.egg/pjsua2.py", line 7196, in transportCreate
    return _pjsua2.Endpoint_transportCreate(self, type, cfg)
pjsua2.Error
21:44:13.790           pjsua_core.c  Shutting down, flags=0...
21:44:13.790           pjsua_core.c  PJSUA state changed: INIT --> CLOSING
21:44:13.790           pjsua_call.c  .Hangup all calls..
21:44:13.790          pjsua_media.c  .Call 0: deinitializing media..
21:44:13.790          pjsua_media.c  .Call 1: deinitializing media..
21:44:13.790          pjsua_media.c  .Call 2: deinitializing media..
21:44:13.790          pjsua_media.c  .Call 3: deinitializing media..
21:44:13.790           pjsua_pres.c  .Shutting down presence..
21:44:14.794           pjsua_core.c  .Destroying...
21:44:14.795          pjsua_media.c  .Shutting down media..
21:44:14.795            pjsua_aud.c  ...Closing null sound device..
21:44:14.808      sip_transaction.c  .Stopping transaction layer module
21:44:14.808      sip_transaction.c  .Stopped transaction layer module
21:44:14.808         sip_endpoint.c  .Module "mod-pjsua-options" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-pjsua-im" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-pjsua-pres" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-pjsua" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-stateful-util" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-refer" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-mwi" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-presence" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-evsub" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-invite" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-100rel" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-ua" unregistered
21:44:14.808      sip_transaction.c  .Transaction layer module destroyed
21:44:14.808         sip_endpoint.c  .Module "mod-tsx-layer" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-msg-print" unregistered
21:44:14.808         sip_endpoint.c  .Module "mod-pjsua-log" unregistered
21:44:14.809                timer.c  .Dumping timer heap:
21:44:14.809                timer.c  .  Cur size: 0 entries, max: 3070
21:44:14.809         sip_endpoint.c  .Endpoint 0x7f97403408 destroyed
21:44:14.809           pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
21:44:14.809           pjsua_core.c  .PJSUA destroyed...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by arnonym** [comment]
The port specified in your config is already in use. I guess you're running the "Voice over IP" service also, which is listening on the same port. Change one to run on a different port.

**Comment by arnonym** [comment]
Closed because of inactivity.

**Comment by orxaz** [comment]
Hi,

Same problem here...

Where do I to configure nameserver? My operating system is correctly configured, resolving DNS queries flawlessly, but I don't know why de plugin always says me this:

```
11:17:05.760         sip_endpoint.c  .Module "mod-pjsua-log" registered
11:17:05.776           pjsua_core.c  .Error setting nameserver: Invalid DNS nameserver address (PJLIB_UTIL_EDNSINNSADDR) [status=320044]
11:17:05.776           endpoint.cpp  pjsua_init(&ua_cfg, &log_cfg, &med_cfg) error: Invalid DNS nameserver address (PJLIB_UTIL_EDNSINNSADDR) (status=320044) [../src/pjsua2/endpoint.cpp:1969]
Traceback (most recent call last):
```

**Comment by orxaz** [comment]
Sorry, I have answered to the wrong thread.
