### ISSUE TITLE
Incoming Call Transfers

### ISSUE THREAD

**Issue by cefranco76** [arnonym/ha-plugins#58]
Hello,

It`ll be possible in the future incoming call transfers?

Thanks.

**Comment by arnonym** [comment]
Hi,

you can already transfer active calls:
https://github.com/arnonym/ha-plugins#to-transfer-a-call-to-a-different-sip-uri

**Comment by cefranco76** [comment]
Well, when I dial to an extension configured in sip_1 and then execute a transfer using STDIN command, I receive the following message:

| 15:46:18.520947 [ ] Warning: call not in progress: sip:6000@192.168.1.40:8088

![image](https://github.com/arnonym/ha-plugins/assets/48095213/e09b79bf-de4b-42dc-85b5-f2543cad0a80)

![image](https://github.com/arnonym/ha-plugins/assets/48095213/512e404b-40d9-4e43-abc5-d94e03ab1840)

But if I dial using STDIN, the call is transfered. Maybe I`m missing something.

**Comment by arnonym** [comment]
That's currently a bit unlucky in how ha-sip identifies calls. for outgoing calls it uses exactly the string you specified when you dialed the number, for incoming it gets some parsed version of that. In your case that's probably just "6000", but you can look in the logs for "Registering call with id <number>". The number is the identifier you need to use for the transfer. You also can set the log level to "2" if the log is too noisy.

**Comment by cefranco76** [comment]
The incoming call identify for transfer worked well and the STDIN command did its job, but...

If I place the same stdin command in an automation I get the following log message:

![image](https://github.com/arnonym/ha-plugins/assets/48095213/a09f7c0c-921f-4058-b898-b94bb7deef4f)

![image](https://github.com/arnonym/ha-plugins/assets/48095213/efef8122-8513-4378-b620-be699eaddec9)

I've already tried the input parameter "number:" without quotes, single and double quotes, with the same result.

**Comment by arnonym** [comment]
For some reason the trailing curly brace is missing and I don't have a clue how that can happen. Maybe try "data-template" instead of "data" and hope that home assistant is doing something differently then or check the leading white-space in the yaml for tabs.  :man_shrugging:

**Comment by arnonym** [comment]
Closed because of inactivity.

**Comment by cefranco76** [comment]
Hi,

I've never succeeded transferring calls using automation. If you could test it and report if you get the same behavior I'll appreciate.

Only works if I execute the command STDIN, but if I use an automation, I get the error :"Could not deserialize JSON: "command":"transfer","number":"6002","transfer_to":"sip:6001@192.168.1.40:8088"}" 

with a missing curly bracket.

**Comment by cefranco76** [comment]
> Hi,
> 
> I've never succeeded transferring calls using automation. If you could test it and report if you get the same behavior I'll appreciate.
> 
> Only works if I execute the command STDIN, but if I use an automation, I get the error :"Could not deserialize JSON: "command":"transfer","number":"6002","transfer_to":"sip:6001@192.168.1.40:8088"}"
> 
> with a missing curly bracket.



Forget about it, after several tests I got the point. The problem was related to webhooks triggering automations. For some reason action is not properly executed. I solved the issue adding a 3 seconds delay before action to be executed and works fine.
