### ISSUE TITLE
Where to put the default configuration info?

### ISSUE THREAD

**Issue by whi4** [arnonym/ha-plugins#60]
Hi,

This is the first add-on that I am aware of that uses hassio.addon_stdin.

You provide default configuration info in the Readme but I get errors if I copy it into the usual /config/configuration.yaml

Where should I put the configuration info for this add-on?

Thanks,    Robert

**Comment by arnonym** [comment]
Hi,

you can edit the configuration in home-assistant by going to "Settings -> Add-ons -> ha-sip" and then click "Configuration" in the middle top of the screen. There you can also look into the logs which is helpful to get everythings running.

Arne

**Comment by whi4** [comment]
Thanks
