### ISSUE TITLE
Google Translate issue

### ISSUE THREAD

**Issue by jamesking210** [arnonym/ha-plugins#63]
Since my 2023.7 upgrade, outbound TTS calls are a solid beep and logs show error getting tts.
Previous to 2023.7 my google translate say was set up via yaml... now it is set up in gui (default settings for us english)

I spun up a fresh HA 2023.7 machine on a separate network just to make sure the issue wasn't an issue with my hardware or config.
anyone else have the same issue & How can i fix?

![Screenshot 2023-07-19 000350](https://github.com/arnonym/ha-plugins/assets/51187832/d6ba9aaa-05be-4365-a8a4-72147b1cbb81)
![Screenshot 2023-07-19 000025](https://github.com/arnonym/ha-plugins/assets/51187832/0aae046e-b453-4649-ad3f-d62f88d7485b)

**Comment by arnonym** [comment]
NCO3 on the community forums had a similar issue and posted this as a solution: https://community.home-assistant.io/t/home-assistant-sip-gateway/333694/120

Hopefully this helps to solve your issue

**Comment by jamesking210** [comment]
I figured it out with Google_translate (google_say)
under system -> network - make sure your external HA URL is listed under Internet. (https://yoururl.duckdns.com)
Re-Added tts: to my config but left out base_url
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

in the config of ha-sip add-on under TTS i added
platform: google_translate
language: en
service_name: google_say

adding the service_name: google_say is what fixed it for me.

**Comment by arnonym** [comment]
Nice you figured that out, but the "service_name" in the ha-sip config does nothing, as this is not used from ha-sip, so you might remove that and try again.
