### ISSUE TITLE
slug name validation

### ISSUE THREAD

**Issue by RedWolf112** [arnonym/ha-plugins#66]
The slug name for this projects seems to be incorrect. 
With the new version 2023.9.0 the slug names get validated. 
As seperator only underscore is allowed.

https://github.com/home-assistant/core/pull/99232

**Comment by arnonym** [comment]
Should be fixed in 3.0, of course you need to change all your stdin calls. I don't know if you need to uninstall and reinstall the add-on to get it running again. Please try and report back!

**Comment by RedWolf112** [comment]
Thanks! Yes, I had to reinstall and restart the system
