### ISSUE TITLE
Home Assistant 2023.9

### ISSUE THREAD

**Issue by jamesking210** [arnonym/ha-plugins#68]
HA-SIP not working with this Version

No logs even pull up for me

**Comment by arnonym** [comment]
Can you try to uninstall and install again? Copy your config sections into a text file before. Also you might need to restart home-assistant. The required change of the slug does not go well with home-assistant.

**Comment by riddlenl** [comment]
Same issue here. Rebooted HA and removed/installed ha-sip

Hostname
c7744bff-ha-sip

**Comment by arnonym** [comment]
Hostname to be used in the stdin action must be `c7744bff_ha_sip`. Does ha-sip boot up, do you see an output in the logs?

**Comment by riddlenl** [comment]
https://i.gyazo.com/a57aabf5a2a0c33e1bc23ae9394dde13.png

HA-sip is registered on my PBX

With c7744bff-ha-sip: invalid slug c7744bff-ha-sip (try c7744bff_ha_sip) for dictionary value @ data['addon']. Got None

Changing it to c7744bff_ha_sip worked now I did a complete reboot of the VM instead of HA restart :-)
HA still shows the 'old' hostname

**Comment by arnonym** [comment]
Hostname is not the same as the slug (that's shown in the URL if you're in the plug-ins config). But I can see where the confusion comes from. Happy you've got it working again!

**Comment by arnonym** [comment]
@jamesking210 did you get it running again?

**Comment by jamesking210** [comment]
been silent because i got sick. no covid, but was down for the count. I rolled my main instance and test machine back to 2023.08.4, I am waiting on a few UPS batteries to arrive tomorrow to get my test bench back to normal. this weekend I should be able to dedicate my time to figuring out what is going on. for those in this thread, i use voip.ms.... registrar_uri: sip:chicago4.voip.ms

**Comment by jamesking210** [comment]
I'm closing this issue because after upgrading from 2023.8.4 to 2023.9.2 everything works as usual.

**Comment by arnonym** [comment]
Just to clarify for me: you still updated ha-sip to 3.0 and changed the slug used in the stdin actions to underscore only?

**Comment by arnonym** [comment]
Also https://github.com/home-assistant/core/pull/100070 changed the slug validation back to the previous behavior :see_no_evil:

**Comment by jamesking210** [comment]
@arnonym nothing changed on my end from 2023.8.4 to 2023.9.2 - i'm still on 2.9 for ha-sip with auto-update on & when i click "changelog" i get: "Addon c7744bff_ha-sip with version latest does not exist in the store"
![Screenshot 2023-09-14 005151](https://github.com/arnonym/ha-plugins/assets/51187832/50b184a3-e21b-433b-bcd3-86c0e24be414)
![Screenshot 2023-09-14 003949](https://github.com/arnonym/ha-plugins/assets/51187832/96b5eb01-52d6-4aa4-9305-ab6ad242342e)

**Comment by jamesking210** [comment]
> Also [home-assistant/core#100070](https://github.com/home-assistant/core/pull/100070) changed the slug validation back to the previous behavior 🙈

this probably fixed it, because nothing was changed on my end on my production HA and it all works - inbound and outbound - ha-sip 2.9 - HA 2023.9.2 OS 10.5

**Comment by arnonym** [comment]
The problem is, you will never get to install a new version. So the question is, if I revert that change and let all the people on 3.0 (I don't know how many) change back the slug again, or leave it like that and all people on 2.9 need to uninstall and reinstall again. Thanks home assistant!

**Comment by arnonym** [comment]
There is no concept of beta versions for add-ons, so there is no easy way to do that except doing a totally separate repository. I just released 3.1 with the updated pjsip and slug changes reverted. Keep me updated!
