### ISSUE TITLE
Extend the README with an example how an external number need to be called via Fritzbox

### ISSUE THREAD

**Issue by brlnr23** [arnonym/ha-plugins#71]
first off: it's more a request of extending the readme by probably one or two lines. To avoid the overhead of a PR and merging, I decided to create an issue. Sorry for that :) 

What I want to suggest: 
It drove me nuts several hours & days to figure out how the format of an external telephone number (in this case my mobile) should look like for an outgoing call. 
Based on the Readme, internal calls to a second local FB connected fone were no issue at all - but it took me a while to figure out that the format of external numbers need to look like this (and excuse me- SIP is completely new to me. Maybe it's a nobrainer for all of you)
"sip:+49...@fritz.box" (or alternatively with the fritzbox IP "sip:+49...@192.168.178.1"

It would be awesome if something like this can be added to the readme to save time for other newbies in the future :) 
Maybe something like, added to the section ot [Outgoing Calls](https://github.com/arnonym/ha-plugins#outgoing-calls)

> Note: When calling an external number the format need to look like `sip:+49123456789@fritz.box`

**Comment by Knallix** [comment]
Hello,
with +49 you come from Germany right?
Can you possibly help me with the connection to the Fritzbox. Unfortunately I can't get a connection.
Thx

**Comment by arnonym** [comment]
Hi @Knallix, you first need to create a SIP user through the web interface of your fritz.box and use this in the config of ha-sip. Not sure where you are struggling, so a few more details would help here.

**Comment by arnonym** [comment]
I've added an example for an external number to the README
