### ISSUE TITLE
Problem registering with voip.ms

### ISSUE THREAD

**Issue by iku777** [arnonym/ha-plugins#74]
Hi,

Just installed the newest version (3.2). To be clear, I hadn't used this addon before.
I am struggling to get my HA registered on a sub-account. I have checked the sub-account works fine but HA cannot register to it.
I saw someone else in here who seems to have managed to get this addon working with Voip.ms. Am I missing something?

![Screenshot 2023-12-14 112248](https://github.com/arnonym/ha-plugins/assets/82530487/4d8e197f-691e-43d9-ad15-66286027f65c)

**Comment by arnonym** [comment]
Hey there, I don't have a voip.ms account, but some of your settings looks fishy.

The `name_server` setting ins normally not needed, and houston1 isn't probably a name server, so I would remove that.

Your `id_uri` setting looks also wrong, probably it's something like `your_phone_number@voip.ms` or `your_voip_ms_username@voip.ms`. Maybe including the houston1 part after the @.

**Comment by arnonym** [comment]
Closed because of inactivity.
