### ISSUE TITLE
Get own phone number on call in webhook

### ISSUE THREAD

**Issue by Feuerhamster** [arnonym/ha-plugins#78]
I am trying to do an automation where I need the exact number that is called on an incoming call.

So, the sip client has the internal phone number `**635` for example. In my phone system, I can append whatever I want to it and the call will still be routed correctly. What I am trying to do is something like `**635#1` will call an automation that do different stuff based on the digit after the `#`. 

As far as I tested it, the call gets through, but in the triggered webhook I cannot find the number that is called (e.g. `**635#1`) but I need that to check in my automation.

Would it be possible to add the exact number that is called as a property to the webhook data?

**Comment by gerard33** [comment]
According to [this](https://github.com/arnonym/ha-plugins/issues/26#issuecomment-1412288764) response in another issue it's not possible to know the called number.

**Comment by arnonym** [comment]
Thanks @gerard33! I looked into that some time ago, and could not find that information in the data available from pjsip. If I missed something, it would be easy to make it available in the webhook data.
