### ISSUE TITLE
HA-SIP crashes at first call

### ISSUE THREAD

**Issue by AarvdH** [arnonym/ha-plugins#88]
Hello,
Thank you for this great integration!
I had my homeassistant on a HP-T630 and the HA-SIP integration was running just fine with my incoming calls (FritzBox)
But now I restored my configuration to my actual environment which is a OdroidN2 +  (quad-core ARM Cortex-A73 CPU)
Is there knowledge that the HA-SIP integration cant rin on a ARM CPU?
At the first call HA_SIP crashes, If I call then immediately after the first call I am getting my menu. As said, all worked fine on the HP-T630.

This is what the supervisor logs says:
24-01-18 14:54:13 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon ha-sip is failed, restarting...

24-01-18 17:07:04 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon ha-sip is failed, restarting...

Any idea how I maybe can solve this?
Thank you.

Versions of it all are all up to date till 18-01-2024
Hans

**Comment by arnonym** [comment]
I'm using ha-sip on a raspberry pi 4, which should be the same architecture, and I also get some random crashes from time to time which I could not get hold of. Maybe it's pjsip, maybe my code does something wrong. I unfortunately can't help you with that currently.

**Comment by AarvdH** [comment]
Too bad, but thank you for the quick answer...

**Comment by arnonym** [comment]
Can you re-check with the current version?

**Comment by AarvdH** [comment]
Hi,
No sorry but either the T630 as the OdroidN2 are both not in use anymore. But I can tell you that it all works perfect with a Intel NUC i5.
Thanks for your effort.
